### ISSUE TITLE
volumio: any RPi architecture?

### ISSUE THREAD

**Issue by paulo-graca** [jbonjean/docker-public#2]
Hi, thank you for contributing with your volumio image. I'm looking for a RPi 4 (ARM) architecture docker image to use in my RPi with HomeAssistant. Do you know any project? Thanks in advance!

**Comment by jbonjean** [comment]
No sorry, I only use Volumio on x86, I don't know any ARM image.

**Comment by paulo-graca** [comment]
Thank you!
